const WIDGET_SPEC = {
  icon: '🎯',
  title: '局部重绘',
  fields: [
    { key: 'service_url', label: '推理服务 service_url', kind: 'text', mono: true },
    { key: 'image', label: '待重绘的图像对象 ID（image）', kind: 'text', mono: true },
    { key: 'model_ref', label: '模型引用 ID（重绘采样用）（model_ref）', kind: 'text', mono: true },
    { key: 'positive', label: '正向 conditioning 对象 ID（positive）', kind: 'text', mono: true },
    { key: 'negative', label: '反向 conditioning 对象 ID（negative）', kind: 'text', mono: true },
    { key: 'detector', label: '检测目标：face（脸部）/ hand（手部）（detector）', kind: 'text', default: 'face' },
    { key: 'denoise', label: '重绘强度 0~1：越高改动越大（denoise）', kind: 'slider', min: 0, max: 1, step: 0.01, default: 0.4 },
    { key: 'steps', label: '重绘采样步数（steps）', kind: 'slider', min: 1, max: 150, step: 1, default: 20 },
    { key: 'conf', label: '检测置信度阈值 0~1（conf）', kind: 'slider', min: 0, max: 1, step: 0.05, default: 0.3 },
    { key: 'padding', label: '检测框外扩比例（0.4 = 四周各扩 40%）（padding）', kind: 'slider', min: 0, max: 1, step: 0.05, default: 0.4 },
    { key: 'guide_size', label: '裁剪区域重绘前放大到的短边像素（guide_size）', kind: 'text', default: 512 },
    { key: 'cfg', label: '重绘 CFG（cfg）', kind: 'slider', min: 1, max: 30, step: 0.5, default: 7.0 },
    { key: 'sampler_name', label: '采样器（更新公式）：euler / euler_（sampler_name）', kind: 'select', options: ['euler', 'euler_a', 'ddim', 'lms', 'dpmpp_2m', 'dpmpp_2m_sde', 'uni_pc'], default: 'euler' },
    { key: 'scheduler', label: 'sigma 排布：normal / karras（scheduler）', kind: 'select', options: ['normal', 'karras', 'exponential', 'beta'], default: 'normal' },
    { key: 'seed', label: '重绘种子（seed）', kind: 'text', default: -1 },
    { key: 'max_targets', label: '最多重绘的目标数（按置信度从高到低取）（max_targets）', kind: 'text', default: 4 },
    { key: 'feather', label: '贴回时的边缘羽化像素（feather）', kind: 'text', default: 16 },
    { key: 'service_token', label: 'service_token（可空）', kind: 'text', mono: true },
  ],
  note: 'ADetailer 式局部重绘',
}
