const WIDGET_SPEC = {
  icon: '🎬',
  title: '视频生成',
  fields: [
    { key: 'service_url', label: '推理服务 service_url', kind: 'text', mono: true },
    { key: 'model_ref', label: '视频模型引用 ID（model_ref）', kind: 'text', mono: true },
    { key: 'prompt', label: '正向提示词（视频内容/运动描述）（prompt）', kind: 'text', mono: true },
    { key: 'negative_prompt', label: '反向提示词（negative_prompt）', kind: 'text', mono: true },
    { key: 'image', label: '首帧 IMAGE 对象 ID（image）', kind: 'text', mono: true },
    { key: 'width', label: '宽度（width）', kind: 'text', default: 832 },
    { key: 'height', label: '高度（height）', kind: 'text', default: 480 },
    { key: 'num_frames', label: '帧数（121 帧 @24fps ≈ 5 秒）（num_frames）', kind: 'text', default: 121 },
    { key: 'fps', label: '帧率（fps）', kind: 'text', default: 24 },
    { key: 'steps', label: '采样步数（steps）', kind: 'slider', min: 1, max: 150, step: 1, default: 50 },
    { key: 'cfg', label: '引导强度（cfg）', kind: 'slider', min: 1, max: 30, step: 0.5, default: 5.0 },
    { key: 'seed', label: '随机种子（seed）', kind: 'text', default: -1 },
    { key: 'preview_every', label: 'preview_every（0=关）', kind: 'text', default: 5 },
    { key: 'poll_interval', label: 'poll_interval（秒）', kind: 'text', default: 5 },
    { key: 'job_timeout', label: 'job_timeout（秒）', kind: 'text', default: 7200 },
    { key: 'decode_chunk_size', label: 'VAE 分块解码帧数（decode_chunk_size）', kind: 'text', default: 0 },
    { key: 'output_mode', label: '输出模式：pil=采样+解码一体输出 VIDEO（output_mode）', kind: 'text', default: 'pil' },
    { key: 'service_token', label: 'service_token（可空）', kind: 'text', mono: true },
  ],
  previewEveryKey: 'preview_every',
  note: '文/图生视频',
}
